spring:
  jpa:
    .database-platform: org.hibernate.dialect.MySQLDialect
    .show-sql: false
    .hibernate:
      .ddl-auto: none
  datasource:
    .url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/films
    .username: root
    .password: 
    .driver-class-name: com.mysql.cj.jdbc.Driver
